version: "3.8"

services:
  admin_app:
    build: .
    command: >
      /bin/sh -c "alembic -c src/alembic.ini upgrade head && uvicorn src.main:app --reload --host 0.0.0.0 --port 8100 --workers 4"
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - ./:/backend
    ports:
      - "8100:8100"
    depends_on:
      - admin_db

  admin_db:
    image: postgres:latest
    container_name: admin_db
    ports:
      - "5434:5434"
    env_file:
      - ./.env.dev.db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: -p 5434
