"""edit fields

Revision ID: 1a5d173401dc
Revises: 7e2cc10a7c16
Create Date: 2024-07-02 10:09:27.812259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5d173401dc'
down_revision: Union[str, None] = '7e2cc10a7c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_metric', sa.Column('words_amount', sa.Integer(), nullable=True))
    op.add_column('global_metric', sa.Column('userwords_amount', sa.Integer(), nullable=True))
    op.add_column('global_metric', sa.Column('learned_amount', sa.Integer(), nullable=True))
    op.add_column('global_metric', sa.Column('learned_percents', sa.Float(), nullable=True))
    op.add_column('global_metric', sa.Column('speech_seconds', sa.Integer(), nullable=True))
    op.add_column('global_metric', sa.Column('video_seconds', sa.Integer(), nullable=True))
    op.drop_column('global_metric', 'today_userwords_amount')
    op.drop_column('global_metric', 'today_speech_seconds')
    op.drop_column('global_metric', 'today_learned_percents')
    op.drop_column('global_metric', 'today_words_amount')
    op.drop_column('global_metric', 'today_video_seconds')
    op.drop_column('global_metric', 'today_learned_amount')
    op.add_column('user_metric', sa.Column('words_amount', sa.Integer(), nullable=True))
    op.add_column('user_metric', sa.Column('userwords_amount', sa.Integer(), nullable=True))
    op.add_column('user_metric', sa.Column('learned_amount', sa.Integer(), nullable=True))
    op.add_column('user_metric', sa.Column('learned_percents', sa.Float(), nullable=True))
    op.add_column('user_metric', sa.Column('speech_seconds', sa.Integer(), nullable=True))
    op.add_column('user_metric', sa.Column('video_seconds', sa.Integer(), nullable=True))
    op.drop_column('user_metric', 'today_userwords_amount')
    op.drop_column('user_metric', 'today_speech_seconds')
    op.drop_column('user_metric', 'today_learned_percents')
    op.drop_column('user_metric', 'today_words_amount')
    op.drop_column('user_metric', 'today_video_seconds')
    op.drop_column('user_metric', 'today_learned_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_metric', sa.Column('today_learned_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_metric', sa.Column('today_video_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_metric', sa.Column('today_words_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_metric', sa.Column('today_learned_percents', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user_metric', sa.Column('today_speech_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_metric', sa.Column('today_userwords_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_metric', 'video_seconds')
    op.drop_column('user_metric', 'speech_seconds')
    op.drop_column('user_metric', 'learned_percents')
    op.drop_column('user_metric', 'learned_amount')
    op.drop_column('user_metric', 'userwords_amount')
    op.drop_column('user_metric', 'words_amount')
    op.add_column('global_metric', sa.Column('today_learned_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('global_metric', sa.Column('today_video_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('global_metric', sa.Column('today_words_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('global_metric', sa.Column('today_learned_percents', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('global_metric', sa.Column('today_speech_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('global_metric', sa.Column('today_userwords_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('global_metric', 'video_seconds')
    op.drop_column('global_metric', 'speech_seconds')
    op.drop_column('global_metric', 'learned_percents')
    op.drop_column('global_metric', 'learned_amount')
    op.drop_column('global_metric', 'userwords_amount')
    op.drop_column('global_metric', 'words_amount')
    # ### end Alembic commands ###
