"""empty message

Revision ID: 4c3b899a0b45
Revises: 
Create Date: 2024-08-27 13:57:27.244201

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c3b899a0b45"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_admin_email"), "admin", ["email"], unique=True)
    op.create_table(
        "global_metric",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alltime_words_amount", sa.Integer(), nullable=True),
        sa.Column("alltime_userwords_amount", sa.Integer(), nullable=True),
        sa.Column("alltime_learned_amount", sa.Integer(), nullable=True),
        sa.Column("alltime_learned_percents", sa.Float(), nullable=True),
        sa.Column("alltime_speech_seconds", sa.Integer(), nullable=True),
        sa.Column("alltime_video_seconds", sa.Integer(), nullable=True),
        sa.Column("words_amount", sa.Integer(), nullable=True),
        sa.Column("userwords_amount", sa.Integer(), nullable=True),
        sa.Column("learned_amount", sa.Integer(), nullable=True),
        sa.Column("learned_percents", sa.Float(), nullable=True),
        sa.Column("speech_seconds", sa.Integer(), nullable=True),
        sa.Column("video_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_global_metric_id"), "global_metric", ["id"], unique=False)
    op.create_table(
        "user_metric",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alltime_userwords_amount", sa.Integer(), nullable=True),
        sa.Column("alltime_learned_amount", sa.Integer(), nullable=True),
        sa.Column("alltime_learned_percents", sa.Float(), nullable=True),
        sa.Column("alltime_speech_seconds", sa.Integer(), nullable=True),
        sa.Column("alltime_video_seconds", sa.Integer(), nullable=True),
        sa.Column("words_amount", sa.Integer(), nullable=True),
        sa.Column("userwords_amount", sa.Integer(), nullable=True),
        sa.Column("learned_amount", sa.Integer(), nullable=True),
        sa.Column("learned_percents", sa.Float(), nullable=True),
        sa.Column("speech_seconds", sa.Integer(), nullable=True),
        sa.Column("video_seconds", sa.Integer(), nullable=True),
        sa.Column("uwords_uid", sa.String(), nullable=False),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_metric_id"), "user_metric", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_metric_id"), table_name="user_metric")
    op.drop_table("user_metric")
    op.drop_index(op.f("ix_global_metric_id"), table_name="global_metric")
    op.drop_table("global_metric")
    op.drop_index(op.f("ix_admin_email"), table_name="admin")
    op.drop_table("admin")
    # ### end Alembic commands ###
